
:-['tools.pro','globalConstraints.pro','pairwisegenerator.pro' ].
:-use_module(library(atts)).

 :- attribute ftAttr/2 , lstAttr/1.



a(catalogmanagement,catalogmanagement,[null,1,2]).
a(catalogmanagement,stockmanagement,[and,0,2]).
a(catalogmanagement,itemassociations,[null,1,3]).
a(catalogmanagement,services,[null,1,3]).
a(catalogmanagement,identification,[null,1,3]).
a(catalogmanagement,itemclassification,[null,1,3]).
a(catalogmanagement,items,[null,1,3]).
a(catalogmanagement,rfid,[null,1,4]).
a(catalogmanagement,barcode,[null,1,4]).
a(catalogmanagement,categories,[null,1,4]).
a(catalogmanagement,tags,[null,1,4]).
a(catalogmanagement,generic,[null,1,4]).
a(catalogmanagement,assembly,[null,1,4]).
a(catalogmanagement,perishable,[null,1,4]).
a(catalogmanagement,serialized,[null,1,4]).
a(catalogmanagement,rawmaterial,[null,1,4]).
a(catalogmanagement,transactions,[and,0,3]).
a(catalogmanagement,unitsconversion,[and,0,3]).
a(catalogmanagement,physicalcounting,[and,0,3]).
a(catalogmanagement,valuationmethod,[and,0,3]).
a(catalogmanagement,inventorymethod,[and,0,3]).
a(catalogmanagement,warehousemanagement,[and,0,3]).
a(catalogmanagement,serialtracking,[and,0,3]).
a(catalogmanagement,expirationcontrol,[and,0,3]).
a(catalogmanagement,increase,[and,0,4]).
a(catalogmanagement,decrease,[and,0,4]).
a(catalogmanagement,transfer,[and,0,4]).
a(catalogmanagement,adjustment,[and,0,4]).
a(catalogmanagement,consignment,[and,0,4]).
a(catalogmanagement,allocation,[and,0,4]).
a(catalogmanagement,assembling,[and,0,4]).
a(catalogmanagement,fifo,[and,0,4]).
a(catalogmanagement,lifo,[and,0,4]).
a(catalogmanagement,avg,[and,0,4]).
a(catalogmanagement,perpetual,[and,0,4]).
a(catalogmanagement,periodic,[and,0,4]).
a(catalogmanagement,inventory,[and,0,1]).
a(stockmanagement,catalogmanagement,[and,0,2]).
a(stockmanagement,stockmanagement,[null,1,2]).
a(stockmanagement,itemassociations,[and,0,3]).
a(stockmanagement,services,[and,0,3]).
a(stockmanagement,identification,[and,0,3]).
a(stockmanagement,itemclassification,[and,0,3]).
a(stockmanagement,items,[and,0,3]).
a(stockmanagement,rfid,[and,0,4]).
a(stockmanagement,barcode,[and,0,4]).
a(stockmanagement,categories,[and,0,4]).
a(stockmanagement,tags,[and,0,4]).
a(stockmanagement,generic,[and,0,4]).
a(stockmanagement,assembly,[and,0,4]).
a(stockmanagement,perishable,[and,0,4]).
a(stockmanagement,serialized,[and,0,4]).
a(stockmanagement,rawmaterial,[and,0,4]).
a(stockmanagement,transactions,[null,1,3]).
a(stockmanagement,unitsconversion,[null,1,3]).
a(stockmanagement,physicalcounting,[null,1,3]).
a(stockmanagement,valuationmethod,[null,1,3]).
a(stockmanagement,inventorymethod,[null,1,3]).
a(stockmanagement,warehousemanagement,[null,1,3]).
a(stockmanagement,serialtracking,[null,1,3]).
a(stockmanagement,expirationcontrol,[null,1,3]).
a(stockmanagement,increase,[null,1,4]).
a(stockmanagement,decrease,[null,1,4]).
a(stockmanagement,transfer,[null,1,4]).
a(stockmanagement,adjustment,[null,1,4]).
a(stockmanagement,consignment,[null,1,4]).
a(stockmanagement,allocation,[null,1,4]).
a(stockmanagement,assembling,[null,1,4]).
a(stockmanagement,fifo,[null,1,4]).
a(stockmanagement,lifo,[null,1,4]).
a(stockmanagement,avg,[null,1,4]).
a(stockmanagement,perpetual,[null,1,4]).
a(stockmanagement,periodic,[null,1,4]).
a(stockmanagement,inventory,[and,0,1]).
a(itemassociations,catalogmanagement,[null,1,3]).
a(itemassociations,stockmanagement,[and,0,3]).
a(itemassociations,itemassociations,[null,2,4]).
a(itemassociations,services,[null,1,4]).
a(itemassociations,identification,[null,1,4]).
a(itemassociations,itemclassification,[null,1,4]).
a(itemassociations,items,[null,1,4]).
a(itemassociations,rfid,[null,1,5]).
a(itemassociations,barcode,[null,1,5]).
a(itemassociations,categories,[null,1,5]).
a(itemassociations,tags,[null,1,5]).
a(itemassociations,generic,[null,1,5]).
a(itemassociations,assembly,[null,1,5]).
a(itemassociations,perishable,[null,1,5]).
a(itemassociations,serialized,[null,1,5]).
a(itemassociations,rawmaterial,[null,1,5]).
a(itemassociations,transactions,[and,0,4]).
a(itemassociations,unitsconversion,[and,0,4]).
a(itemassociations,physicalcounting,[and,0,4]).
a(itemassociations,valuationmethod,[and,0,4]).
a(itemassociations,inventorymethod,[and,0,4]).
a(itemassociations,warehousemanagement,[and,0,4]).
a(itemassociations,serialtracking,[and,0,4]).
a(itemassociations,expirationcontrol,[and,0,4]).
a(itemassociations,increase,[and,0,5]).
a(itemassociations,decrease,[and,0,5]).
a(itemassociations,transfer,[and,0,5]).
a(itemassociations,adjustment,[and,0,5]).
a(itemassociations,consignment,[and,0,5]).
a(itemassociations,allocation,[and,0,5]).
a(itemassociations,assembling,[and,0,5]).
a(itemassociations,fifo,[and,0,5]).
a(itemassociations,lifo,[and,0,5]).
a(itemassociations,avg,[and,0,5]).
a(itemassociations,perpetual,[and,0,5]).
a(itemassociations,periodic,[and,0,5]).
a(itemassociations,inventory,[and,0,2]).
a(services,catalogmanagement,[null,1,3]).
a(services,stockmanagement,[and,0,3]).
a(services,itemassociations,[null,1,4]).
a(services,services,[null,2,4]).
a(services,identification,[null,1,4]).
a(services,itemclassification,[null,1,4]).
a(services,items,[null,1,4]).
a(services,rfid,[null,1,5]).
a(services,barcode,[null,1,5]).
a(services,categories,[null,1,5]).
a(services,tags,[null,1,5]).
a(services,generic,[null,1,5]).
a(services,assembly,[null,1,5]).
a(services,perishable,[null,1,5]).
a(services,serialized,[null,1,5]).
a(services,rawmaterial,[null,1,5]).
a(services,transactions,[and,0,4]).
a(services,unitsconversion,[and,0,4]).
a(services,physicalcounting,[and,0,4]).
a(services,valuationmethod,[and,0,4]).
a(services,inventorymethod,[and,0,4]).
a(services,warehousemanagement,[and,0,4]).
a(services,serialtracking,[and,0,4]).
a(services,expirationcontrol,[and,0,4]).
a(services,increase,[and,0,5]).
a(services,decrease,[and,0,5]).
a(services,transfer,[and,0,5]).
a(services,adjustment,[and,0,5]).
a(services,consignment,[and,0,5]).
a(services,allocation,[and,0,5]).
a(services,assembling,[and,0,5]).
a(services,fifo,[and,0,5]).
a(services,lifo,[and,0,5]).
a(services,avg,[and,0,5]).
a(services,perpetual,[and,0,5]).
a(services,periodic,[and,0,5]).
a(services,inventory,[and,0,2]).
a(identification,catalogmanagement,[null,1,3]).
a(identification,stockmanagement,[and,0,3]).
a(identification,itemassociations,[null,1,4]).
a(identification,services,[null,1,4]).
a(identification,identification,[or,2,4]).
a(identification,itemclassification,[null,1,4]).
a(identification,items,[null,1,4]).
a(identification,rfid,[or,2,5]).
a(identification,barcode,[or,2,5]).
a(identification,categories,[null,1,5]).
a(identification,tags,[null,1,5]).
a(identification,generic,[null,1,5]).
a(identification,assembly,[null,1,5]).
a(identification,perishable,[null,1,5]).
a(identification,serialized,[null,1,5]).
a(identification,rawmaterial,[null,1,5]).
a(identification,transactions,[and,0,4]).
a(identification,unitsconversion,[and,0,4]).
a(identification,physicalcounting,[and,0,4]).
a(identification,valuationmethod,[and,0,4]).
a(identification,inventorymethod,[and,0,4]).
a(identification,warehousemanagement,[and,0,4]).
a(identification,serialtracking,[and,0,4]).
a(identification,expirationcontrol,[and,0,4]).
a(identification,increase,[and,0,5]).
a(identification,decrease,[and,0,5]).
a(identification,transfer,[and,0,5]).
a(identification,adjustment,[and,0,5]).
a(identification,consignment,[and,0,5]).
a(identification,allocation,[and,0,5]).
a(identification,assembling,[and,0,5]).
a(identification,fifo,[and,0,5]).
a(identification,lifo,[and,0,5]).
a(identification,avg,[and,0,5]).
a(identification,perpetual,[and,0,5]).
a(identification,periodic,[and,0,5]).
a(identification,inventory,[and,0,2]).
a(itemclassification,catalogmanagement,[null,1,3]).
a(itemclassification,stockmanagement,[and,0,3]).
a(itemclassification,itemassociations,[null,1,4]).
a(itemclassification,services,[null,1,4]).
a(itemclassification,identification,[null,1,4]).
a(itemclassification,itemclassification,[or,2,4]).
a(itemclassification,items,[null,1,4]).
a(itemclassification,rfid,[null,1,5]).
a(itemclassification,barcode,[null,1,5]).
a(itemclassification,categories,[or,2,5]).
a(itemclassification,tags,[or,2,5]).
a(itemclassification,generic,[null,1,5]).
a(itemclassification,assembly,[null,1,5]).
a(itemclassification,perishable,[null,1,5]).
a(itemclassification,serialized,[null,1,5]).
a(itemclassification,rawmaterial,[null,1,5]).
a(itemclassification,transactions,[and,0,4]).
a(itemclassification,unitsconversion,[and,0,4]).
a(itemclassification,physicalcounting,[and,0,4]).
a(itemclassification,valuationmethod,[and,0,4]).
a(itemclassification,inventorymethod,[and,0,4]).
a(itemclassification,warehousemanagement,[and,0,4]).
a(itemclassification,serialtracking,[and,0,4]).
a(itemclassification,expirationcontrol,[and,0,4]).
a(itemclassification,increase,[and,0,5]).
a(itemclassification,decrease,[and,0,5]).
a(itemclassification,transfer,[and,0,5]).
a(itemclassification,adjustment,[and,0,5]).
a(itemclassification,consignment,[and,0,5]).
a(itemclassification,allocation,[and,0,5]).
a(itemclassification,assembling,[and,0,5]).
a(itemclassification,fifo,[and,0,5]).
a(itemclassification,lifo,[and,0,5]).
a(itemclassification,avg,[and,0,5]).
a(itemclassification,perpetual,[and,0,5]).
a(itemclassification,periodic,[and,0,5]).
a(itemclassification,inventory,[and,0,2]).
a(items,catalogmanagement,[null,1,3]).
a(items,stockmanagement,[and,0,3]).
a(items,itemassociations,[null,1,4]).
a(items,services,[null,1,4]).
a(items,identification,[null,1,4]).
a(items,itemclassification,[null,1,4]).
a(items,items,[or,2,4]).
a(items,rfid,[null,1,5]).
a(items,barcode,[null,1,5]).
a(items,categories,[null,1,5]).
a(items,tags,[null,1,5]).
a(items,generic,[or,2,5]).
a(items,assembly,[or,2,5]).
a(items,perishable,[or,2,5]).
a(items,serialized,[or,2,5]).
a(items,rawmaterial,[or,2,5]).
a(items,transactions,[and,0,4]).
a(items,unitsconversion,[and,0,4]).
a(items,physicalcounting,[and,0,4]).
a(items,valuationmethod,[and,0,4]).
a(items,inventorymethod,[and,0,4]).
a(items,warehousemanagement,[and,0,4]).
a(items,serialtracking,[and,0,4]).
a(items,expirationcontrol,[and,0,4]).
a(items,increase,[and,0,5]).
a(items,decrease,[and,0,5]).
a(items,transfer,[and,0,5]).
a(items,adjustment,[and,0,5]).
a(items,consignment,[and,0,5]).
a(items,allocation,[and,0,5]).
a(items,assembling,[and,0,5]).
a(items,fifo,[and,0,5]).
a(items,lifo,[and,0,5]).
a(items,avg,[and,0,5]).
a(items,perpetual,[and,0,5]).
a(items,periodic,[and,0,5]).
a(items,inventory,[and,0,2]).
a(rfid,catalogmanagement,[null,1,4]).
a(rfid,stockmanagement,[and,0,4]).
a(rfid,itemassociations,[null,1,5]).
a(rfid,services,[null,1,5]).
a(rfid,identification,[or,2,5]).
a(rfid,itemclassification,[null,1,5]).
a(rfid,items,[null,1,5]).
a(rfid,rfid,[null,3,6]).
a(rfid,barcode,[or,2,6]).
a(rfid,categories,[null,1,6]).
a(rfid,tags,[null,1,6]).
a(rfid,generic,[null,1,6]).
a(rfid,assembly,[null,1,6]).
a(rfid,perishable,[null,1,6]).
a(rfid,serialized,[null,1,6]).
a(rfid,rawmaterial,[null,1,6]).
a(rfid,transactions,[and,0,5]).
a(rfid,unitsconversion,[and,0,5]).
a(rfid,physicalcounting,[and,0,5]).
a(rfid,valuationmethod,[and,0,5]).
a(rfid,inventorymethod,[and,0,5]).
a(rfid,warehousemanagement,[and,0,5]).
a(rfid,serialtracking,[and,0,5]).
a(rfid,expirationcontrol,[and,0,5]).
a(rfid,increase,[and,0,6]).
a(rfid,decrease,[and,0,6]).
a(rfid,transfer,[and,0,6]).
a(rfid,adjustment,[and,0,6]).
a(rfid,consignment,[and,0,6]).
a(rfid,allocation,[and,0,6]).
a(rfid,assembling,[and,0,6]).
a(rfid,fifo,[and,0,6]).
a(rfid,lifo,[and,0,6]).
a(rfid,avg,[and,0,6]).
a(rfid,perpetual,[and,0,6]).
a(rfid,periodic,[and,0,6]).
a(rfid,inventory,[and,0,3]).
a(barcode,catalogmanagement,[null,1,4]).
a(barcode,stockmanagement,[and,0,4]).
a(barcode,itemassociations,[null,1,5]).
a(barcode,services,[null,1,5]).
a(barcode,identification,[or,2,5]).
a(barcode,itemclassification,[null,1,5]).
a(barcode,items,[null,1,5]).
a(barcode,rfid,[or,2,6]).
a(barcode,barcode,[null,3,6]).
a(barcode,categories,[null,1,6]).
a(barcode,tags,[null,1,6]).
a(barcode,generic,[null,1,6]).
a(barcode,assembly,[null,1,6]).
a(barcode,perishable,[null,1,6]).
a(barcode,serialized,[null,1,6]).
a(barcode,rawmaterial,[null,1,6]).
a(barcode,transactions,[and,0,5]).
a(barcode,unitsconversion,[and,0,5]).
a(barcode,physicalcounting,[and,0,5]).
a(barcode,valuationmethod,[and,0,5]).
a(barcode,inventorymethod,[and,0,5]).
a(barcode,warehousemanagement,[and,0,5]).
a(barcode,serialtracking,[and,0,5]).
a(barcode,expirationcontrol,[and,0,5]).
a(barcode,increase,[and,0,6]).
a(barcode,decrease,[and,0,6]).
a(barcode,transfer,[and,0,6]).
a(barcode,adjustment,[and,0,6]).
a(barcode,consignment,[and,0,6]).
a(barcode,allocation,[and,0,6]).
a(barcode,assembling,[and,0,6]).
a(barcode,fifo,[and,0,6]).
a(barcode,lifo,[and,0,6]).
a(barcode,avg,[and,0,6]).
a(barcode,perpetual,[and,0,6]).
a(barcode,periodic,[and,0,6]).
a(barcode,inventory,[and,0,3]).
a(categories,catalogmanagement,[null,1,4]).
a(categories,stockmanagement,[and,0,4]).
a(categories,itemassociations,[null,1,5]).
a(categories,services,[null,1,5]).
a(categories,identification,[null,1,5]).
a(categories,itemclassification,[or,2,5]).
a(categories,items,[null,1,5]).
a(categories,rfid,[null,1,6]).
a(categories,barcode,[null,1,6]).
a(categories,categories,[null,3,6]).
a(categories,tags,[or,2,6]).
a(categories,generic,[and,1,6]).
a(categories,assembly,[and,1,6]).
a(categories,perishable,[and,1,6]).
a(categories,serialized,[and,1,6]).
a(categories,rawmaterial,[and,1,6]).
a(categories,transactions,[and,0,5]).
a(categories,unitsconversion,[and,0,5]).
a(categories,physicalcounting,[and,0,5]).
a(categories,valuationmethod,[and,0,5]).
a(categories,inventorymethod,[and,0,5]).
a(categories,warehousemanagement,[and,0,5]).
a(categories,serialtracking,[and,0,5]).
a(categories,expirationcontrol,[and,0,5]).
a(categories,increase,[and,0,6]).
a(categories,decrease,[and,0,6]).
a(categories,transfer,[and,0,6]).
a(categories,adjustment,[and,0,6]).
a(categories,consignment,[and,0,6]).
a(categories,allocation,[and,0,6]).
a(categories,assembling,[and,0,6]).
a(categories,fifo,[and,0,6]).
a(categories,lifo,[and,0,6]).
a(categories,avg,[and,0,6]).
a(categories,perpetual,[and,0,6]).
a(categories,periodic,[and,0,6]).
a(categories,inventory,[and,0,3]).
a(tags,catalogmanagement,[null,1,4]).
a(tags,stockmanagement,[and,0,4]).
a(tags,itemassociations,[null,1,5]).
a(tags,services,[null,1,5]).
a(tags,identification,[null,1,5]).
a(tags,itemclassification,[or,2,5]).
a(tags,items,[null,1,5]).
a(tags,rfid,[null,1,6]).
a(tags,barcode,[null,1,6]).
a(tags,categories,[or,2,6]).
a(tags,tags,[null,3,6]).
a(tags,generic,[and,1,6]).
a(tags,assembly,[and,1,6]).
a(tags,perishable,[and,1,6]).
a(tags,serialized,[and,1,6]).
a(tags,rawmaterial,[and,1,6]).
a(tags,transactions,[and,0,5]).
a(tags,unitsconversion,[and,0,5]).
a(tags,physicalcounting,[and,0,5]).
a(tags,valuationmethod,[and,0,5]).
a(tags,inventorymethod,[and,0,5]).
a(tags,warehousemanagement,[and,0,5]).
a(tags,serialtracking,[and,0,5]).
a(tags,expirationcontrol,[and,0,5]).
a(tags,increase,[and,0,6]).
a(tags,decrease,[and,0,6]).
a(tags,transfer,[and,0,6]).
a(tags,adjustment,[and,0,6]).
a(tags,consignment,[and,0,6]).
a(tags,allocation,[and,0,6]).
a(tags,assembling,[and,0,6]).
a(tags,fifo,[and,0,6]).
a(tags,lifo,[and,0,6]).
a(tags,avg,[and,0,6]).
a(tags,perpetual,[and,0,6]).
a(tags,periodic,[and,0,6]).
a(tags,inventory,[and,0,3]).
a(generic,catalogmanagement,[null,1,4]).
a(generic,stockmanagement,[and,0,4]).
a(generic,itemassociations,[null,1,5]).
a(generic,services,[null,1,5]).
a(generic,identification,[null,1,5]).
a(generic,itemclassification,[null,1,5]).
a(generic,items,[or,2,5]).
a(generic,rfid,[null,1,6]).
a(generic,barcode,[null,1,6]).
a(generic,categories,[and,1,6]).
a(generic,tags,[and,1,6]).
a(generic,generic,[null,3,6]).
a(generic,assembly,[or,2,6]).
a(generic,perishable,[or,2,6]).
a(generic,serialized,[or,2,6]).
a(generic,rawmaterial,[or,2,6]).
a(generic,transactions,[and,0,5]).
a(generic,unitsconversion,[and,0,5]).
a(generic,physicalcounting,[and,0,5]).
a(generic,valuationmethod,[and,0,5]).
a(generic,inventorymethod,[and,0,5]).
a(generic,warehousemanagement,[and,0,5]).
a(generic,serialtracking,[and,0,5]).
a(generic,expirationcontrol,[and,0,5]).
a(generic,increase,[and,0,6]).
a(generic,decrease,[and,0,6]).
a(generic,transfer,[and,0,6]).
a(generic,adjustment,[and,0,6]).
a(generic,consignment,[and,0,6]).
a(generic,allocation,[and,0,6]).
a(generic,assembling,[and,0,6]).
a(generic,fifo,[and,0,6]).
a(generic,lifo,[and,0,6]).
a(generic,avg,[and,0,6]).
a(generic,perpetual,[and,0,6]).
a(generic,periodic,[and,0,6]).
a(generic,inventory,[and,0,3]).
a(assembly,catalogmanagement,[null,1,4]).
a(assembly,stockmanagement,[and,0,4]).
a(assembly,itemassociations,[null,1,5]).
a(assembly,services,[null,1,5]).
a(assembly,identification,[null,1,5]).
a(assembly,itemclassification,[null,1,5]).
a(assembly,items,[or,2,5]).
a(assembly,rfid,[null,1,6]).
a(assembly,barcode,[null,1,6]).
a(assembly,categories,[and,1,6]).
a(assembly,tags,[and,1,6]).
a(assembly,generic,[or,2,6]).
a(assembly,assembly,[null,3,6]).
a(assembly,perishable,[or,2,6]).
a(assembly,serialized,[or,2,6]).
a(assembly,rawmaterial,[or,2,6]).
a(assembly,transactions,[and,0,5]).
a(assembly,unitsconversion,[and,0,5]).
a(assembly,physicalcounting,[and,0,5]).
a(assembly,valuationmethod,[and,0,5]).
a(assembly,inventorymethod,[and,0,5]).
a(assembly,warehousemanagement,[and,0,5]).
a(assembly,serialtracking,[and,0,5]).
a(assembly,expirationcontrol,[and,0,5]).
a(assembly,increase,[and,0,6]).
a(assembly,decrease,[and,0,6]).
a(assembly,transfer,[and,0,6]).
a(assembly,adjustment,[and,0,6]).
a(assembly,consignment,[and,0,6]).
a(assembly,allocation,[and,0,6]).
a(assembly,assembling,[and,0,6]).
a(assembly,fifo,[and,0,6]).
a(assembly,lifo,[and,0,6]).
a(assembly,avg,[and,0,6]).
a(assembly,perpetual,[and,0,6]).
a(assembly,periodic,[and,0,6]).
a(assembly,inventory,[and,0,3]).
a(perishable,catalogmanagement,[null,1,4]).
a(perishable,stockmanagement,[and,0,4]).
a(perishable,itemassociations,[null,1,5]).
a(perishable,services,[null,1,5]).
a(perishable,identification,[null,1,5]).
a(perishable,itemclassification,[null,1,5]).
a(perishable,items,[or,2,5]).
a(perishable,rfid,[null,1,6]).
a(perishable,barcode,[null,1,6]).
a(perishable,categories,[and,1,6]).
a(perishable,tags,[and,1,6]).
a(perishable,generic,[or,2,6]).
a(perishable,assembly,[or,2,6]).
a(perishable,perishable,[null,3,6]).
a(perishable,serialized,[or,2,6]).
a(perishable,rawmaterial,[or,2,6]).
a(perishable,transactions,[and,0,5]).
a(perishable,unitsconversion,[and,0,5]).
a(perishable,physicalcounting,[and,0,5]).
a(perishable,valuationmethod,[and,0,5]).
a(perishable,inventorymethod,[and,0,5]).
a(perishable,warehousemanagement,[and,0,5]).
a(perishable,serialtracking,[and,0,5]).
a(perishable,expirationcontrol,[and,0,5]).
a(perishable,increase,[and,0,6]).
a(perishable,decrease,[and,0,6]).
a(perishable,transfer,[and,0,6]).
a(perishable,adjustment,[and,0,6]).
a(perishable,consignment,[and,0,6]).
a(perishable,allocation,[and,0,6]).
a(perishable,assembling,[and,0,6]).
a(perishable,fifo,[and,0,6]).
a(perishable,lifo,[and,0,6]).
a(perishable,avg,[and,0,6]).
a(perishable,perpetual,[and,0,6]).
a(perishable,periodic,[and,0,6]).
a(perishable,inventory,[and,0,3]).
a(serialized,catalogmanagement,[null,1,4]).
a(serialized,stockmanagement,[and,0,4]).
a(serialized,itemassociations,[null,1,5]).
a(serialized,services,[null,1,5]).
a(serialized,identification,[null,1,5]).
a(serialized,itemclassification,[null,1,5]).
a(serialized,items,[or,2,5]).
a(serialized,rfid,[null,1,6]).
a(serialized,barcode,[null,1,6]).
a(serialized,categories,[and,1,6]).
a(serialized,tags,[and,1,6]).
a(serialized,generic,[or,2,6]).
a(serialized,assembly,[or,2,6]).
a(serialized,perishable,[or,2,6]).
a(serialized,serialized,[null,3,6]).
a(serialized,rawmaterial,[or,2,6]).
a(serialized,transactions,[and,0,5]).
a(serialized,unitsconversion,[and,0,5]).
a(serialized,physicalcounting,[and,0,5]).
a(serialized,valuationmethod,[and,0,5]).
a(serialized,inventorymethod,[and,0,5]).
a(serialized,warehousemanagement,[and,0,5]).
a(serialized,serialtracking,[and,0,5]).
a(serialized,expirationcontrol,[and,0,5]).
a(serialized,increase,[and,0,6]).
a(serialized,decrease,[and,0,6]).
a(serialized,transfer,[and,0,6]).
a(serialized,adjustment,[and,0,6]).
a(serialized,consignment,[and,0,6]).
a(serialized,allocation,[and,0,6]).
a(serialized,assembling,[and,0,6]).
a(serialized,fifo,[and,0,6]).
a(serialized,lifo,[and,0,6]).
a(serialized,avg,[and,0,6]).
a(serialized,perpetual,[and,0,6]).
a(serialized,periodic,[and,0,6]).
a(serialized,inventory,[and,0,3]).
a(rawmaterial,catalogmanagement,[null,1,4]).
a(rawmaterial,stockmanagement,[and,0,4]).
a(rawmaterial,itemassociations,[null,1,5]).
a(rawmaterial,services,[null,1,5]).
a(rawmaterial,identification,[null,1,5]).
a(rawmaterial,itemclassification,[null,1,5]).
a(rawmaterial,items,[or,2,5]).
a(rawmaterial,rfid,[null,1,6]).
a(rawmaterial,barcode,[null,1,6]).
a(rawmaterial,categories,[and,1,6]).
a(rawmaterial,tags,[and,1,6]).
a(rawmaterial,generic,[or,2,6]).
a(rawmaterial,assembly,[or,2,6]).
a(rawmaterial,perishable,[or,2,6]).
a(rawmaterial,serialized,[or,2,6]).
a(rawmaterial,rawmaterial,[null,3,6]).
a(rawmaterial,transactions,[and,0,5]).
a(rawmaterial,unitsconversion,[and,0,5]).
a(rawmaterial,physicalcounting,[and,0,5]).
a(rawmaterial,valuationmethod,[and,0,5]).
a(rawmaterial,inventorymethod,[and,0,5]).
a(rawmaterial,warehousemanagement,[and,0,5]).
a(rawmaterial,serialtracking,[and,0,5]).
a(rawmaterial,expirationcontrol,[and,0,5]).
a(rawmaterial,increase,[and,0,6]).
a(rawmaterial,decrease,[and,0,6]).
a(rawmaterial,transfer,[and,0,6]).
a(rawmaterial,adjustment,[and,0,6]).
a(rawmaterial,consignment,[and,0,6]).
a(rawmaterial,allocation,[and,0,6]).
a(rawmaterial,assembling,[and,0,6]).
a(rawmaterial,fifo,[and,0,6]).
a(rawmaterial,lifo,[and,0,6]).
a(rawmaterial,avg,[and,0,6]).
a(rawmaterial,perpetual,[and,0,6]).
a(rawmaterial,periodic,[and,0,6]).
a(rawmaterial,inventory,[and,0,3]).
a(transactions,catalogmanagement,[and,0,3]).
a(transactions,stockmanagement,[null,1,3]).
a(transactions,itemassociations,[and,0,4]).
a(transactions,services,[and,0,4]).
a(transactions,identification,[and,0,4]).
a(transactions,itemclassification,[and,0,4]).
a(transactions,items,[and,0,4]).
a(transactions,rfid,[and,0,5]).
a(transactions,barcode,[and,0,5]).
a(transactions,categories,[and,0,5]).
a(transactions,tags,[and,0,5]).
a(transactions,generic,[and,0,5]).
a(transactions,assembly,[and,0,5]).
a(transactions,perishable,[and,0,5]).
a(transactions,serialized,[and,0,5]).
a(transactions,rawmaterial,[and,0,5]).
a(transactions,transactions,[or,2,4]).
a(transactions,unitsconversion,[null,1,4]).
a(transactions,physicalcounting,[null,1,4]).
a(transactions,valuationmethod,[null,1,4]).
a(transactions,inventorymethod,[null,1,4]).
a(transactions,warehousemanagement,[null,1,4]).
a(transactions,serialtracking,[null,1,4]).
a(transactions,expirationcontrol,[null,1,4]).
a(transactions,increase,[or,2,5]).
a(transactions,decrease,[or,2,5]).
a(transactions,transfer,[or,2,5]).
a(transactions,adjustment,[or,2,5]).
a(transactions,consignment,[or,2,5]).
a(transactions,allocation,[or,2,5]).
a(transactions,assembling,[or,2,5]).
a(transactions,fifo,[null,1,5]).
a(transactions,lifo,[null,1,5]).
a(transactions,avg,[null,1,5]).
a(transactions,perpetual,[null,1,5]).
a(transactions,periodic,[null,1,5]).
a(transactions,inventory,[and,0,2]).
a(unitsconversion,catalogmanagement,[and,0,3]).
a(unitsconversion,stockmanagement,[null,1,3]).
a(unitsconversion,itemassociations,[and,0,4]).
a(unitsconversion,services,[and,0,4]).
a(unitsconversion,identification,[and,0,4]).
a(unitsconversion,itemclassification,[and,0,4]).
a(unitsconversion,items,[and,0,4]).
a(unitsconversion,rfid,[and,0,5]).
a(unitsconversion,barcode,[and,0,5]).
a(unitsconversion,categories,[and,0,5]).
a(unitsconversion,tags,[and,0,5]).
a(unitsconversion,generic,[and,0,5]).
a(unitsconversion,assembly,[and,0,5]).
a(unitsconversion,perishable,[and,0,5]).
a(unitsconversion,serialized,[and,0,5]).
a(unitsconversion,rawmaterial,[and,0,5]).
a(unitsconversion,transactions,[null,1,4]).
a(unitsconversion,unitsconversion,[null,2,4]).
a(unitsconversion,physicalcounting,[null,1,4]).
a(unitsconversion,valuationmethod,[null,1,4]).
a(unitsconversion,inventorymethod,[null,1,4]).
a(unitsconversion,warehousemanagement,[null,1,4]).
a(unitsconversion,serialtracking,[null,1,4]).
a(unitsconversion,expirationcontrol,[null,1,4]).
a(unitsconversion,increase,[null,1,5]).
a(unitsconversion,decrease,[null,1,5]).
a(unitsconversion,transfer,[null,1,5]).
a(unitsconversion,adjustment,[null,1,5]).
a(unitsconversion,consignment,[null,1,5]).
a(unitsconversion,allocation,[null,1,5]).
a(unitsconversion,assembling,[null,1,5]).
a(unitsconversion,fifo,[null,1,5]).
a(unitsconversion,lifo,[null,1,5]).
a(unitsconversion,avg,[null,1,5]).
a(unitsconversion,perpetual,[null,1,5]).
a(unitsconversion,periodic,[null,1,5]).
a(unitsconversion,inventory,[and,0,2]).
a(physicalcounting,catalogmanagement,[and,0,3]).
a(physicalcounting,stockmanagement,[null,1,3]).
a(physicalcounting,itemassociations,[and,0,4]).
a(physicalcounting,services,[and,0,4]).
a(physicalcounting,identification,[and,0,4]).
a(physicalcounting,itemclassification,[and,0,4]).
a(physicalcounting,items,[and,0,4]).
a(physicalcounting,rfid,[and,0,5]).
a(physicalcounting,barcode,[and,0,5]).
a(physicalcounting,categories,[and,0,5]).
a(physicalcounting,tags,[and,0,5]).
a(physicalcounting,generic,[and,0,5]).
a(physicalcounting,assembly,[and,0,5]).
a(physicalcounting,perishable,[and,0,5]).
a(physicalcounting,serialized,[and,0,5]).
a(physicalcounting,rawmaterial,[and,0,5]).
a(physicalcounting,transactions,[null,1,4]).
a(physicalcounting,unitsconversion,[null,1,4]).
a(physicalcounting,physicalcounting,[null,2,4]).
a(physicalcounting,valuationmethod,[null,1,4]).
a(physicalcounting,inventorymethod,[null,1,4]).
a(physicalcounting,warehousemanagement,[null,1,4]).
a(physicalcounting,serialtracking,[null,1,4]).
a(physicalcounting,expirationcontrol,[null,1,4]).
a(physicalcounting,increase,[null,1,5]).
a(physicalcounting,decrease,[null,1,5]).
a(physicalcounting,transfer,[null,1,5]).
a(physicalcounting,adjustment,[null,1,5]).
a(physicalcounting,consignment,[null,1,5]).
a(physicalcounting,allocation,[null,1,5]).
a(physicalcounting,assembling,[null,1,5]).
a(physicalcounting,fifo,[null,1,5]).
a(physicalcounting,lifo,[null,1,5]).
a(physicalcounting,avg,[null,1,5]).
a(physicalcounting,perpetual,[null,1,5]).
a(physicalcounting,periodic,[null,1,5]).
a(physicalcounting,inventory,[and,0,2]).
a(valuationmethod,catalogmanagement,[and,0,3]).
a(valuationmethod,stockmanagement,[null,1,3]).
a(valuationmethod,itemassociations,[and,0,4]).
a(valuationmethod,services,[and,0,4]).
a(valuationmethod,identification,[and,0,4]).
a(valuationmethod,itemclassification,[and,0,4]).
a(valuationmethod,items,[and,0,4]).
a(valuationmethod,rfid,[and,0,5]).
a(valuationmethod,barcode,[and,0,5]).
a(valuationmethod,categories,[and,0,5]).
a(valuationmethod,tags,[and,0,5]).
a(valuationmethod,generic,[and,0,5]).
a(valuationmethod,assembly,[and,0,5]).
a(valuationmethod,perishable,[and,0,5]).
a(valuationmethod,serialized,[and,0,5]).
a(valuationmethod,rawmaterial,[and,0,5]).
a(valuationmethod,transactions,[null,1,4]).
a(valuationmethod,unitsconversion,[null,1,4]).
a(valuationmethod,physicalcounting,[null,1,4]).
a(valuationmethod,valuationmethod,[xor,2,4]).
a(valuationmethod,inventorymethod,[null,1,4]).
a(valuationmethod,warehousemanagement,[null,1,4]).
a(valuationmethod,serialtracking,[null,1,4]).
a(valuationmethod,expirationcontrol,[null,1,4]).
a(valuationmethod,increase,[null,1,5]).
a(valuationmethod,decrease,[null,1,5]).
a(valuationmethod,transfer,[null,1,5]).
a(valuationmethod,adjustment,[null,1,5]).
a(valuationmethod,consignment,[null,1,5]).
a(valuationmethod,allocation,[null,1,5]).
a(valuationmethod,assembling,[null,1,5]).
a(valuationmethod,fifo,[xor,2,5]).
a(valuationmethod,lifo,[xor,2,5]).
a(valuationmethod,avg,[xor,2,5]).
a(valuationmethod,perpetual,[null,1,5]).
a(valuationmethod,periodic,[null,1,5]).
a(valuationmethod,inventory,[and,0,2]).
a(inventorymethod,catalogmanagement,[and,0,3]).
a(inventorymethod,stockmanagement,[null,1,3]).
a(inventorymethod,itemassociations,[and,0,4]).
a(inventorymethod,services,[and,0,4]).
a(inventorymethod,identification,[and,0,4]).
a(inventorymethod,itemclassification,[and,0,4]).
a(inventorymethod,items,[and,0,4]).
a(inventorymethod,rfid,[and,0,5]).
a(inventorymethod,barcode,[and,0,5]).
a(inventorymethod,categories,[and,0,5]).
a(inventorymethod,tags,[and,0,5]).
a(inventorymethod,generic,[and,0,5]).
a(inventorymethod,assembly,[and,0,5]).
a(inventorymethod,perishable,[and,0,5]).
a(inventorymethod,serialized,[and,0,5]).
a(inventorymethod,rawmaterial,[and,0,5]).
a(inventorymethod,transactions,[null,1,4]).
a(inventorymethod,unitsconversion,[null,1,4]).
a(inventorymethod,physicalcounting,[null,1,4]).
a(inventorymethod,valuationmethod,[null,1,4]).
a(inventorymethod,inventorymethod,[xor,2,4]).
a(inventorymethod,warehousemanagement,[null,1,4]).
a(inventorymethod,serialtracking,[null,1,4]).
a(inventorymethod,expirationcontrol,[null,1,4]).
a(inventorymethod,increase,[null,1,5]).
a(inventorymethod,decrease,[null,1,5]).
a(inventorymethod,transfer,[null,1,5]).
a(inventorymethod,adjustment,[null,1,5]).
a(inventorymethod,consignment,[null,1,5]).
a(inventorymethod,allocation,[null,1,5]).
a(inventorymethod,assembling,[null,1,5]).
a(inventorymethod,fifo,[null,1,5]).
a(inventorymethod,lifo,[null,1,5]).
a(inventorymethod,avg,[null,1,5]).
a(inventorymethod,perpetual,[xor,2,5]).
a(inventorymethod,periodic,[xor,2,5]).
a(inventorymethod,inventory,[and,0,2]).
a(warehousemanagement,catalogmanagement,[and,0,3]).
a(warehousemanagement,stockmanagement,[null,1,3]).
a(warehousemanagement,itemassociations,[and,0,4]).
a(warehousemanagement,services,[and,0,4]).
a(warehousemanagement,identification,[and,0,4]).
a(warehousemanagement,itemclassification,[and,0,4]).
a(warehousemanagement,items,[and,0,4]).
a(warehousemanagement,rfid,[and,0,5]).
a(warehousemanagement,barcode,[and,0,5]).
a(warehousemanagement,categories,[and,0,5]).
a(warehousemanagement,tags,[and,0,5]).
a(warehousemanagement,generic,[and,0,5]).
a(warehousemanagement,assembly,[and,0,5]).
a(warehousemanagement,perishable,[and,0,5]).
a(warehousemanagement,serialized,[and,0,5]).
a(warehousemanagement,rawmaterial,[and,0,5]).
a(warehousemanagement,transactions,[null,1,4]).
a(warehousemanagement,unitsconversion,[null,1,4]).
a(warehousemanagement,physicalcounting,[null,1,4]).
a(warehousemanagement,valuationmethod,[null,1,4]).
a(warehousemanagement,inventorymethod,[null,1,4]).
a(warehousemanagement,warehousemanagement,[null,2,4]).
a(warehousemanagement,serialtracking,[null,1,4]).
a(warehousemanagement,expirationcontrol,[null,1,4]).
a(warehousemanagement,increase,[null,1,5]).
a(warehousemanagement,decrease,[null,1,5]).
a(warehousemanagement,transfer,[null,1,5]).
a(warehousemanagement,adjustment,[null,1,5]).
a(warehousemanagement,consignment,[null,1,5]).
a(warehousemanagement,allocation,[null,1,5]).
a(warehousemanagement,assembling,[null,1,5]).
a(warehousemanagement,fifo,[null,1,5]).
a(warehousemanagement,lifo,[null,1,5]).
a(warehousemanagement,avg,[null,1,5]).
a(warehousemanagement,perpetual,[null,1,5]).
a(warehousemanagement,periodic,[null,1,5]).
a(warehousemanagement,inventory,[and,0,2]).
a(serialtracking,catalogmanagement,[and,0,3]).
a(serialtracking,stockmanagement,[null,1,3]).
a(serialtracking,itemassociations,[and,0,4]).
a(serialtracking,services,[and,0,4]).
a(serialtracking,identification,[and,0,4]).
a(serialtracking,itemclassification,[and,0,4]).
a(serialtracking,items,[and,0,4]).
a(serialtracking,rfid,[and,0,5]).
a(serialtracking,barcode,[and,0,5]).
a(serialtracking,categories,[and,0,5]).
a(serialtracking,tags,[and,0,5]).
a(serialtracking,generic,[and,0,5]).
a(serialtracking,assembly,[and,0,5]).
a(serialtracking,perishable,[and,0,5]).
a(serialtracking,serialized,[and,0,5]).
a(serialtracking,rawmaterial,[and,0,5]).
a(serialtracking,transactions,[null,1,4]).
a(serialtracking,unitsconversion,[null,1,4]).
a(serialtracking,physicalcounting,[null,1,4]).
a(serialtracking,valuationmethod,[null,1,4]).
a(serialtracking,inventorymethod,[null,1,4]).
a(serialtracking,warehousemanagement,[null,1,4]).
a(serialtracking,serialtracking,[null,2,4]).
a(serialtracking,expirationcontrol,[null,1,4]).
a(serialtracking,increase,[null,1,5]).
a(serialtracking,decrease,[null,1,5]).
a(serialtracking,transfer,[null,1,5]).
a(serialtracking,adjustment,[null,1,5]).
a(serialtracking,consignment,[null,1,5]).
a(serialtracking,allocation,[null,1,5]).
a(serialtracking,assembling,[null,1,5]).
a(serialtracking,fifo,[null,1,5]).
a(serialtracking,lifo,[null,1,5]).
a(serialtracking,avg,[null,1,5]).
a(serialtracking,perpetual,[null,1,5]).
a(serialtracking,periodic,[null,1,5]).
a(serialtracking,inventory,[and,0,2]).
a(expirationcontrol,catalogmanagement,[and,0,3]).
a(expirationcontrol,stockmanagement,[null,1,3]).
a(expirationcontrol,itemassociations,[and,0,4]).
a(expirationcontrol,services,[and,0,4]).
a(expirationcontrol,identification,[and,0,4]).
a(expirationcontrol,itemclassification,[and,0,4]).
a(expirationcontrol,items,[and,0,4]).
a(expirationcontrol,rfid,[and,0,5]).
a(expirationcontrol,barcode,[and,0,5]).
a(expirationcontrol,categories,[and,0,5]).
a(expirationcontrol,tags,[and,0,5]).
a(expirationcontrol,generic,[and,0,5]).
a(expirationcontrol,assembly,[and,0,5]).
a(expirationcontrol,perishable,[and,0,5]).
a(expirationcontrol,serialized,[and,0,5]).
a(expirationcontrol,rawmaterial,[and,0,5]).
a(expirationcontrol,transactions,[null,1,4]).
a(expirationcontrol,unitsconversion,[null,1,4]).
a(expirationcontrol,physicalcounting,[null,1,4]).
a(expirationcontrol,valuationmethod,[null,1,4]).
a(expirationcontrol,inventorymethod,[null,1,4]).
a(expirationcontrol,warehousemanagement,[null,1,4]).
a(expirationcontrol,serialtracking,[null,1,4]).
a(expirationcontrol,expirationcontrol,[null,2,4]).
a(expirationcontrol,increase,[null,1,5]).
a(expirationcontrol,decrease,[null,1,5]).
a(expirationcontrol,transfer,[null,1,5]).
a(expirationcontrol,adjustment,[null,1,5]).
a(expirationcontrol,consignment,[null,1,5]).
a(expirationcontrol,allocation,[null,1,5]).
a(expirationcontrol,assembling,[null,1,5]).
a(expirationcontrol,fifo,[null,1,5]).
a(expirationcontrol,lifo,[null,1,5]).
a(expirationcontrol,avg,[null,1,5]).
a(expirationcontrol,perpetual,[null,1,5]).
a(expirationcontrol,periodic,[null,1,5]).
a(expirationcontrol,inventory,[and,0,2]).
a(increase,catalogmanagement,[and,0,4]).
a(increase,stockmanagement,[null,1,4]).
a(increase,itemassociations,[and,0,5]).
a(increase,services,[and,0,5]).
a(increase,identification,[and,0,5]).
a(increase,itemclassification,[and,0,5]).
a(increase,items,[and,0,5]).
a(increase,rfid,[and,0,6]).
a(increase,barcode,[and,0,6]).
a(increase,categories,[and,0,6]).
a(increase,tags,[and,0,6]).
a(increase,generic,[and,0,6]).
a(increase,assembly,[and,0,6]).
a(increase,perishable,[and,0,6]).
a(increase,serialized,[and,0,6]).
a(increase,rawmaterial,[and,0,6]).
a(increase,transactions,[or,2,5]).
a(increase,unitsconversion,[null,1,5]).
a(increase,physicalcounting,[null,1,5]).
a(increase,valuationmethod,[null,1,5]).
a(increase,inventorymethod,[null,1,5]).
a(increase,warehousemanagement,[null,1,5]).
a(increase,serialtracking,[null,1,5]).
a(increase,expirationcontrol,[null,1,5]).
a(increase,increase,[null,3,6]).
a(increase,decrease,[or,2,6]).
a(increase,transfer,[or,2,6]).
a(increase,adjustment,[or,2,6]).
a(increase,consignment,[or,2,6]).
a(increase,allocation,[or,2,6]).
a(increase,assembling,[or,2,6]).
a(increase,fifo,[and,1,6]).
a(increase,lifo,[and,1,6]).
a(increase,avg,[and,1,6]).
a(increase,perpetual,[and,1,6]).
a(increase,periodic,[and,1,6]).
a(increase,inventory,[and,0,3]).
a(decrease,catalogmanagement,[and,0,4]).
a(decrease,stockmanagement,[null,1,4]).
a(decrease,itemassociations,[and,0,5]).
a(decrease,services,[and,0,5]).
a(decrease,identification,[and,0,5]).
a(decrease,itemclassification,[and,0,5]).
a(decrease,items,[and,0,5]).
a(decrease,rfid,[and,0,6]).
a(decrease,barcode,[and,0,6]).
a(decrease,categories,[and,0,6]).
a(decrease,tags,[and,0,6]).
a(decrease,generic,[and,0,6]).
a(decrease,assembly,[and,0,6]).
a(decrease,perishable,[and,0,6]).
a(decrease,serialized,[and,0,6]).
a(decrease,rawmaterial,[and,0,6]).
a(decrease,transactions,[or,2,5]).
a(decrease,unitsconversion,[null,1,5]).
a(decrease,physicalcounting,[null,1,5]).
a(decrease,valuationmethod,[null,1,5]).
a(decrease,inventorymethod,[null,1,5]).
a(decrease,warehousemanagement,[null,1,5]).
a(decrease,serialtracking,[null,1,5]).
a(decrease,expirationcontrol,[null,1,5]).
a(decrease,increase,[or,2,6]).
a(decrease,decrease,[null,3,6]).
a(decrease,transfer,[or,2,6]).
a(decrease,adjustment,[or,2,6]).
a(decrease,consignment,[or,2,6]).
a(decrease,allocation,[or,2,6]).
a(decrease,assembling,[or,2,6]).
a(decrease,fifo,[and,1,6]).
a(decrease,lifo,[and,1,6]).
a(decrease,avg,[and,1,6]).
a(decrease,perpetual,[and,1,6]).
a(decrease,periodic,[and,1,6]).
a(decrease,inventory,[and,0,3]).
a(transfer,catalogmanagement,[and,0,4]).
a(transfer,stockmanagement,[null,1,4]).
a(transfer,itemassociations,[and,0,5]).
a(transfer,services,[and,0,5]).
a(transfer,identification,[and,0,5]).
a(transfer,itemclassification,[and,0,5]).
a(transfer,items,[and,0,5]).
a(transfer,rfid,[and,0,6]).
a(transfer,barcode,[and,0,6]).
a(transfer,categories,[and,0,6]).
a(transfer,tags,[and,0,6]).
a(transfer,generic,[and,0,6]).
a(transfer,assembly,[and,0,6]).
a(transfer,perishable,[and,0,6]).
a(transfer,serialized,[and,0,6]).
a(transfer,rawmaterial,[and,0,6]).
a(transfer,transactions,[or,2,5]).
a(transfer,unitsconversion,[null,1,5]).
a(transfer,physicalcounting,[null,1,5]).
a(transfer,valuationmethod,[null,1,5]).
a(transfer,inventorymethod,[null,1,5]).
a(transfer,warehousemanagement,[null,1,5]).
a(transfer,serialtracking,[null,1,5]).
a(transfer,expirationcontrol,[null,1,5]).
a(transfer,increase,[or,2,6]).
a(transfer,decrease,[or,2,6]).
a(transfer,transfer,[null,3,6]).
a(transfer,adjustment,[or,2,6]).
a(transfer,consignment,[or,2,6]).
a(transfer,allocation,[or,2,6]).
a(transfer,assembling,[or,2,6]).
a(transfer,fifo,[and,1,6]).
a(transfer,lifo,[and,1,6]).
a(transfer,avg,[and,1,6]).
a(transfer,perpetual,[and,1,6]).
a(transfer,periodic,[and,1,6]).
a(transfer,inventory,[and,0,3]).
a(adjustment,catalogmanagement,[and,0,4]).
a(adjustment,stockmanagement,[null,1,4]).
a(adjustment,itemassociations,[and,0,5]).
a(adjustment,services,[and,0,5]).
a(adjustment,identification,[and,0,5]).
a(adjustment,itemclassification,[and,0,5]).
a(adjustment,items,[and,0,5]).
a(adjustment,rfid,[and,0,6]).
a(adjustment,barcode,[and,0,6]).
a(adjustment,categories,[and,0,6]).
a(adjustment,tags,[and,0,6]).
a(adjustment,generic,[and,0,6]).
a(adjustment,assembly,[and,0,6]).
a(adjustment,perishable,[and,0,6]).
a(adjustment,serialized,[and,0,6]).
a(adjustment,rawmaterial,[and,0,6]).
a(adjustment,transactions,[or,2,5]).
a(adjustment,unitsconversion,[null,1,5]).
a(adjustment,physicalcounting,[null,1,5]).
a(adjustment,valuationmethod,[null,1,5]).
a(adjustment,inventorymethod,[null,1,5]).
a(adjustment,warehousemanagement,[null,1,5]).
a(adjustment,serialtracking,[null,1,5]).
a(adjustment,expirationcontrol,[null,1,5]).
a(adjustment,increase,[or,2,6]).
a(adjustment,decrease,[or,2,6]).
a(adjustment,transfer,[or,2,6]).
a(adjustment,adjustment,[null,3,6]).
a(adjustment,consignment,[or,2,6]).
a(adjustment,allocation,[or,2,6]).
a(adjustment,assembling,[or,2,6]).
a(adjustment,fifo,[and,1,6]).
a(adjustment,lifo,[and,1,6]).
a(adjustment,avg,[and,1,6]).
a(adjustment,perpetual,[and,1,6]).
a(adjustment,periodic,[and,1,6]).
a(adjustment,inventory,[and,0,3]).
a(consignment,catalogmanagement,[and,0,4]).
a(consignment,stockmanagement,[null,1,4]).
a(consignment,itemassociations,[and,0,5]).
a(consignment,services,[and,0,5]).
a(consignment,identification,[and,0,5]).
a(consignment,itemclassification,[and,0,5]).
a(consignment,items,[and,0,5]).
a(consignment,rfid,[and,0,6]).
a(consignment,barcode,[and,0,6]).
a(consignment,categories,[and,0,6]).
a(consignment,tags,[and,0,6]).
a(consignment,generic,[and,0,6]).
a(consignment,assembly,[and,0,6]).
a(consignment,perishable,[and,0,6]).
a(consignment,serialized,[and,0,6]).
a(consignment,rawmaterial,[and,0,6]).
a(consignment,transactions,[or,2,5]).
a(consignment,unitsconversion,[null,1,5]).
a(consignment,physicalcounting,[null,1,5]).
a(consignment,valuationmethod,[null,1,5]).
a(consignment,inventorymethod,[null,1,5]).
a(consignment,warehousemanagement,[null,1,5]).
a(consignment,serialtracking,[null,1,5]).
a(consignment,expirationcontrol,[null,1,5]).
a(consignment,increase,[or,2,6]).
a(consignment,decrease,[or,2,6]).
a(consignment,transfer,[or,2,6]).
a(consignment,adjustment,[or,2,6]).
a(consignment,consignment,[null,3,6]).
a(consignment,allocation,[or,2,6]).
a(consignment,assembling,[or,2,6]).
a(consignment,fifo,[and,1,6]).
a(consignment,lifo,[and,1,6]).
a(consignment,avg,[and,1,6]).
a(consignment,perpetual,[and,1,6]).
a(consignment,periodic,[and,1,6]).
a(consignment,inventory,[and,0,3]).
a(allocation,catalogmanagement,[and,0,4]).
a(allocation,stockmanagement,[null,1,4]).
a(allocation,itemassociations,[and,0,5]).
a(allocation,services,[and,0,5]).
a(allocation,identification,[and,0,5]).
a(allocation,itemclassification,[and,0,5]).
a(allocation,items,[and,0,5]).
a(allocation,rfid,[and,0,6]).
a(allocation,barcode,[and,0,6]).
a(allocation,categories,[and,0,6]).
a(allocation,tags,[and,0,6]).
a(allocation,generic,[and,0,6]).
a(allocation,assembly,[and,0,6]).
a(allocation,perishable,[and,0,6]).
a(allocation,serialized,[and,0,6]).
a(allocation,rawmaterial,[and,0,6]).
a(allocation,transactions,[or,2,5]).
a(allocation,unitsconversion,[null,1,5]).
a(allocation,physicalcounting,[null,1,5]).
a(allocation,valuationmethod,[null,1,5]).
a(allocation,inventorymethod,[null,1,5]).
a(allocation,warehousemanagement,[null,1,5]).
a(allocation,serialtracking,[null,1,5]).
a(allocation,expirationcontrol,[null,1,5]).
a(allocation,increase,[or,2,6]).
a(allocation,decrease,[or,2,6]).
a(allocation,transfer,[or,2,6]).
a(allocation,adjustment,[or,2,6]).
a(allocation,consignment,[or,2,6]).
a(allocation,allocation,[null,3,6]).
a(allocation,assembling,[or,2,6]).
a(allocation,fifo,[and,1,6]).
a(allocation,lifo,[and,1,6]).
a(allocation,avg,[and,1,6]).
a(allocation,perpetual,[and,1,6]).
a(allocation,periodic,[and,1,6]).
a(allocation,inventory,[and,0,3]).
a(assembling,catalogmanagement,[and,0,4]).
a(assembling,stockmanagement,[null,1,4]).
a(assembling,itemassociations,[and,0,5]).
a(assembling,services,[and,0,5]).
a(assembling,identification,[and,0,5]).
a(assembling,itemclassification,[and,0,5]).
a(assembling,items,[and,0,5]).
a(assembling,rfid,[and,0,6]).
a(assembling,barcode,[and,0,6]).
a(assembling,categories,[and,0,6]).
a(assembling,tags,[and,0,6]).
a(assembling,generic,[and,0,6]).
a(assembling,assembly,[and,0,6]).
a(assembling,perishable,[and,0,6]).
a(assembling,serialized,[and,0,6]).
a(assembling,rawmaterial,[and,0,6]).
a(assembling,transactions,[or,2,5]).
a(assembling,unitsconversion,[null,1,5]).
a(assembling,physicalcounting,[null,1,5]).
a(assembling,valuationmethod,[null,1,5]).
a(assembling,inventorymethod,[null,1,5]).
a(assembling,warehousemanagement,[null,1,5]).
a(assembling,serialtracking,[null,1,5]).
a(assembling,expirationcontrol,[null,1,5]).
a(assembling,increase,[or,2,6]).
a(assembling,decrease,[or,2,6]).
a(assembling,transfer,[or,2,6]).
a(assembling,adjustment,[or,2,6]).
a(assembling,consignment,[or,2,6]).
a(assembling,allocation,[or,2,6]).
a(assembling,assembling,[null,3,6]).
a(assembling,fifo,[and,1,6]).
a(assembling,lifo,[and,1,6]).
a(assembling,avg,[and,1,6]).
a(assembling,perpetual,[and,1,6]).
a(assembling,periodic,[and,1,6]).
a(assembling,inventory,[and,0,3]).
a(fifo,catalogmanagement,[and,0,4]).
a(fifo,stockmanagement,[null,1,4]).
a(fifo,itemassociations,[and,0,5]).
a(fifo,services,[and,0,5]).
a(fifo,identification,[and,0,5]).
a(fifo,itemclassification,[and,0,5]).
a(fifo,items,[and,0,5]).
a(fifo,rfid,[and,0,6]).
a(fifo,barcode,[and,0,6]).
a(fifo,categories,[and,0,6]).
a(fifo,tags,[and,0,6]).
a(fifo,generic,[and,0,6]).
a(fifo,assembly,[and,0,6]).
a(fifo,perishable,[and,0,6]).
a(fifo,serialized,[and,0,6]).
a(fifo,rawmaterial,[and,0,6]).
a(fifo,transactions,[null,1,5]).
a(fifo,unitsconversion,[null,1,5]).
a(fifo,physicalcounting,[null,1,5]).
a(fifo,valuationmethod,[xor,2,5]).
a(fifo,inventorymethod,[null,1,5]).
a(fifo,warehousemanagement,[null,1,5]).
a(fifo,serialtracking,[null,1,5]).
a(fifo,expirationcontrol,[null,1,5]).
a(fifo,increase,[and,1,6]).
a(fifo,decrease,[and,1,6]).
a(fifo,transfer,[and,1,6]).
a(fifo,adjustment,[and,1,6]).
a(fifo,consignment,[and,1,6]).
a(fifo,allocation,[and,1,6]).
a(fifo,assembling,[and,1,6]).
a(fifo,fifo,[null,3,6]).
a(fifo,lifo,[xor,2,6]).
a(fifo,avg,[xor,2,6]).
a(fifo,perpetual,[and,1,6]).
a(fifo,periodic,[and,1,6]).
a(fifo,inventory,[and,0,3]).
a(lifo,catalogmanagement,[and,0,4]).
a(lifo,stockmanagement,[null,1,4]).
a(lifo,itemassociations,[and,0,5]).
a(lifo,services,[and,0,5]).
a(lifo,identification,[and,0,5]).
a(lifo,itemclassification,[and,0,5]).
a(lifo,items,[and,0,5]).
a(lifo,rfid,[and,0,6]).
a(lifo,barcode,[and,0,6]).
a(lifo,categories,[and,0,6]).
a(lifo,tags,[and,0,6]).
a(lifo,generic,[and,0,6]).
a(lifo,assembly,[and,0,6]).
a(lifo,perishable,[and,0,6]).
a(lifo,serialized,[and,0,6]).
a(lifo,rawmaterial,[and,0,6]).
a(lifo,transactions,[null,1,5]).
a(lifo,unitsconversion,[null,1,5]).
a(lifo,physicalcounting,[null,1,5]).
a(lifo,valuationmethod,[xor,2,5]).
a(lifo,inventorymethod,[null,1,5]).
a(lifo,warehousemanagement,[null,1,5]).
a(lifo,serialtracking,[null,1,5]).
a(lifo,expirationcontrol,[null,1,5]).
a(lifo,increase,[and,1,6]).
a(lifo,decrease,[and,1,6]).
a(lifo,transfer,[and,1,6]).
a(lifo,adjustment,[and,1,6]).
a(lifo,consignment,[and,1,6]).
a(lifo,allocation,[and,1,6]).
a(lifo,assembling,[and,1,6]).
a(lifo,fifo,[xor,2,6]).
a(lifo,lifo,[null,3,6]).
a(lifo,avg,[xor,2,6]).
a(lifo,perpetual,[and,1,6]).
a(lifo,periodic,[and,1,6]).
a(lifo,inventory,[and,0,3]).
a(avg,catalogmanagement,[and,0,4]).
a(avg,stockmanagement,[null,1,4]).
a(avg,itemassociations,[and,0,5]).
a(avg,services,[and,0,5]).
a(avg,identification,[and,0,5]).
a(avg,itemclassification,[and,0,5]).
a(avg,items,[and,0,5]).
a(avg,rfid,[and,0,6]).
a(avg,barcode,[and,0,6]).
a(avg,categories,[and,0,6]).
a(avg,tags,[and,0,6]).
a(avg,generic,[and,0,6]).
a(avg,assembly,[and,0,6]).
a(avg,perishable,[and,0,6]).
a(avg,serialized,[and,0,6]).
a(avg,rawmaterial,[and,0,6]).
a(avg,transactions,[null,1,5]).
a(avg,unitsconversion,[null,1,5]).
a(avg,physicalcounting,[null,1,5]).
a(avg,valuationmethod,[xor,2,5]).
a(avg,inventorymethod,[null,1,5]).
a(avg,warehousemanagement,[null,1,5]).
a(avg,serialtracking,[null,1,5]).
a(avg,expirationcontrol,[null,1,5]).
a(avg,increase,[and,1,6]).
a(avg,decrease,[and,1,6]).
a(avg,transfer,[and,1,6]).
a(avg,adjustment,[and,1,6]).
a(avg,consignment,[and,1,6]).
a(avg,allocation,[and,1,6]).
a(avg,assembling,[and,1,6]).
a(avg,fifo,[xor,2,6]).
a(avg,lifo,[xor,2,6]).
a(avg,avg,[null,3,6]).
a(avg,perpetual,[and,1,6]).
a(avg,periodic,[and,1,6]).
a(avg,inventory,[and,0,3]).
a(perpetual,catalogmanagement,[and,0,4]).
a(perpetual,stockmanagement,[null,1,4]).
a(perpetual,itemassociations,[and,0,5]).
a(perpetual,services,[and,0,5]).
a(perpetual,identification,[and,0,5]).
a(perpetual,itemclassification,[and,0,5]).
a(perpetual,items,[and,0,5]).
a(perpetual,rfid,[and,0,6]).
a(perpetual,barcode,[and,0,6]).
a(perpetual,categories,[and,0,6]).
a(perpetual,tags,[and,0,6]).
a(perpetual,generic,[and,0,6]).
a(perpetual,assembly,[and,0,6]).
a(perpetual,perishable,[and,0,6]).
a(perpetual,serialized,[and,0,6]).
a(perpetual,rawmaterial,[and,0,6]).
a(perpetual,transactions,[null,1,5]).
a(perpetual,unitsconversion,[null,1,5]).
a(perpetual,physicalcounting,[null,1,5]).
a(perpetual,valuationmethod,[null,1,5]).
a(perpetual,inventorymethod,[xor,2,5]).
a(perpetual,warehousemanagement,[null,1,5]).
a(perpetual,serialtracking,[null,1,5]).
a(perpetual,expirationcontrol,[null,1,5]).
a(perpetual,increase,[and,1,6]).
a(perpetual,decrease,[and,1,6]).
a(perpetual,transfer,[and,1,6]).
a(perpetual,adjustment,[and,1,6]).
a(perpetual,consignment,[and,1,6]).
a(perpetual,allocation,[and,1,6]).
a(perpetual,assembling,[and,1,6]).
a(perpetual,fifo,[and,1,6]).
a(perpetual,lifo,[and,1,6]).
a(perpetual,avg,[and,1,6]).
a(perpetual,perpetual,[null,3,6]).
a(perpetual,periodic,[xor,2,6]).
a(perpetual,inventory,[and,0,3]).
a(periodic,catalogmanagement,[and,0,4]).
a(periodic,stockmanagement,[null,1,4]).
a(periodic,itemassociations,[and,0,5]).
a(periodic,services,[and,0,5]).
a(periodic,identification,[and,0,5]).
a(periodic,itemclassification,[and,0,5]).
a(periodic,items,[and,0,5]).
a(periodic,rfid,[and,0,6]).
a(periodic,barcode,[and,0,6]).
a(periodic,categories,[and,0,6]).
a(periodic,tags,[and,0,6]).
a(periodic,generic,[and,0,6]).
a(periodic,assembly,[and,0,6]).
a(periodic,perishable,[and,0,6]).
a(periodic,serialized,[and,0,6]).
a(periodic,rawmaterial,[and,0,6]).
a(periodic,transactions,[null,1,5]).
a(periodic,unitsconversion,[null,1,5]).
a(periodic,physicalcounting,[null,1,5]).
a(periodic,valuationmethod,[null,1,5]).
a(periodic,inventorymethod,[xor,2,5]).
a(periodic,warehousemanagement,[null,1,5]).
a(periodic,serialtracking,[null,1,5]).
a(periodic,expirationcontrol,[null,1,5]).
a(periodic,increase,[and,1,6]).
a(periodic,decrease,[and,1,6]).
a(periodic,transfer,[and,1,6]).
a(periodic,adjustment,[and,1,6]).
a(periodic,consignment,[and,1,6]).
a(periodic,allocation,[and,1,6]).
a(periodic,assembling,[and,1,6]).
a(periodic,fifo,[and,1,6]).
a(periodic,lifo,[and,1,6]).
a(periodic,avg,[and,1,6]).
a(periodic,perpetual,[xor,2,6]).
a(periodic,periodic,[null,3,6]).
a(periodic,inventory,[and,0,3]).
a(inventory,catalogmanagement,[and,0,1]).
a(inventory,stockmanagement,[and,0,1]).
a(inventory,itemassociations,[and,0,2]).
a(inventory,services,[and,0,2]).
a(inventory,identification,[and,0,2]).
a(inventory,itemclassification,[and,0,2]).
a(inventory,items,[and,0,2]).
a(inventory,rfid,[and,0,3]).
a(inventory,barcode,[and,0,3]).
a(inventory,categories,[and,0,3]).
a(inventory,tags,[and,0,3]).
a(inventory,generic,[and,0,3]).
a(inventory,assembly,[and,0,3]).
a(inventory,perishable,[and,0,3]).
a(inventory,serialized,[and,0,3]).
a(inventory,rawmaterial,[and,0,3]).
a(inventory,transactions,[and,0,2]).
a(inventory,unitsconversion,[and,0,2]).
a(inventory,physicalcounting,[and,0,2]).
a(inventory,valuationmethod,[and,0,2]).
a(inventory,inventorymethod,[and,0,2]).
a(inventory,warehousemanagement,[and,0,2]).
a(inventory,serialtracking,[and,0,2]).
a(inventory,expirationcontrol,[and,0,2]).
a(inventory,increase,[and,0,3]).
a(inventory,decrease,[and,0,3]).
a(inventory,transfer,[and,0,3]).
a(inventory,adjustment,[and,0,3]).
a(inventory,consignment,[and,0,3]).
a(inventory,allocation,[and,0,3]).
a(inventory,assembling,[and,0,3]).
a(inventory,fifo,[and,0,3]).
a(inventory,lifo,[and,0,3]).
a(inventory,avg,[and,0,3]).
a(inventory,perpetual,[and,0,3]).
a(inventory,periodic,[and,0,3]).
a(inventory,inventory,[and,0,0]).

test :-LstFt =[CATALOGMANAGEMENT,STOCKMANAGEMENT,ITEMASSOCIATIONS,SERVICES,IDENTIFICATION,ITEMCLASSIFICATION,ITEMS,RFID,BARCODE,CATEGORIES,TAGS,GENERIC,ASSEMBLY,PERISHABLE,SERIALIZED,RAWMATERIAL,TRANSACTIONS,UNITSCONVERSION,PHYSICALCOUNTING,VALUATIONMETHOD,INVENTORYMETHOD,WAREHOUSEMANAGEMENT,SERIALTRACKING,EXPIRATIONCONTROL,INCREASE,DECREASE,TRANSFER,ADJUSTMENT,CONSIGNMENT,ALLOCATION,ASSEMBLING,FIFO,LIFO,AVG,PERPETUAL,PERIODIC,INVENTORY],
 Ctr = [and(INVENTORY,[CATALOGMANAGEMENT,STOCKMANAGEMENT]), opt(CATALOGMANAGEMENT,[ITEMASSOCIATIONS,SERVICES,IDENTIFICATION]),and(CATALOGMANAGEMENT,[ITEMCLASSIFICATION,ITEMS]),   or(IDENTIFICATION,[RFID,BARCODE]),   or(ITEMCLASSIFICATION,[CATEGORIES,TAGS]),   or(ITEMS,[GENERIC,ASSEMBLY,PERISHABLE,SERIALIZED,RAWMATERIAL]),      and(STOCKMANAGEMENT,[TRANSACTIONS,UNITSCONVERSION,PHYSICALCOUNTING,VALUATIONMETHOD,INVENTORYMETHOD]),opt(STOCKMANAGEMENT,[WAREHOUSEMANAGEMENT,SERIALTRACKING,EXPIRATIONCONTROL]), or(TRANSACTIONS,[INCREASE,DECREASE,TRANSFER,ADJUSTMENT,CONSIGNMENT,ALLOCATION,ASSEMBLING]),          xor(VALUATIONMETHOD,[FIFO,LIFO,AVG]),    xor(INVENTORYMETHOD,[PERPETUAL,PERIODIC]),     require(ASSEMBLING,ASSEMBLY),require(TRANSFER,WAREHOUSEMANAGEMENT),require(SERIALTRACKING,IDENTIFICATION),require(PERISHABLE,EXPIRATIONCONTROL),require(SERIALIZED,IDENTIFICATION),require(ASSEMBLY,ITEMASSOCIATIONS)],
 Att = [put_atts(CATALOGMANAGEMENT ,ftAttr(catalogmanagement,_)),put_atts(STOCKMANAGEMENT ,ftAttr(stockmanagement,_)),put_atts(ITEMASSOCIATIONS ,ftAttr(itemassociations,_)),put_atts(SERVICES ,ftAttr(services,_)),put_atts(IDENTIFICATION ,ftAttr(identification,_)),put_atts(ITEMCLASSIFICATION ,ftAttr(itemclassification,_)),put_atts(ITEMS ,ftAttr(items,_)),put_atts(RFID ,ftAttr(rfid,_)),put_atts(BARCODE ,ftAttr(barcode,_)),put_atts(CATEGORIES ,ftAttr(categories,_)),put_atts(TAGS ,ftAttr(tags,_)),put_atts(GENERIC ,ftAttr(generic,_)),put_atts(ASSEMBLY ,ftAttr(assembly,_)),put_atts(PERISHABLE ,ftAttr(perishable,_)),put_atts(SERIALIZED ,ftAttr(serialized,_)),put_atts(RAWMATERIAL ,ftAttr(rawmaterial,_)),put_atts(TRANSACTIONS ,ftAttr(transactions,_)),put_atts(UNITSCONVERSION ,ftAttr(unitsconversion,_)),put_atts(PHYSICALCOUNTING ,ftAttr(physicalcounting,_)),put_atts(VALUATIONMETHOD ,ftAttr(valuationmethod,_)),put_atts(INVENTORYMETHOD ,ftAttr(inventorymethod,_)),put_atts(WAREHOUSEMANAGEMENT ,ftAttr(warehousemanagement,_)),put_atts(SERIALTRACKING ,ftAttr(serialtracking,_)),put_atts(EXPIRATIONCONTROL ,ftAttr(expirationcontrol,_)),put_atts(INCREASE ,ftAttr(increase,_)),put_atts(DECREASE ,ftAttr(decrease,_)),put_atts(TRANSFER ,ftAttr(transfer,_)),put_atts(ADJUSTMENT ,ftAttr(adjustment,_)),put_atts(CONSIGNMENT ,ftAttr(consignment,_)),put_atts(ALLOCATION ,ftAttr(allocation,_)),put_atts(ASSEMBLING ,ftAttr(assembling,_)),put_atts(FIFO ,ftAttr(fifo,_)),put_atts(LIFO ,ftAttr(lifo,_)),put_atts(AVG ,ftAttr(avg,_)),put_atts(PERPETUAL ,ftAttr(perpetual,_)),put_atts(PERIODIC ,ftAttr(periodic,_)),put_atts(INVENTORY ,ftAttr(inventory,1))],
        length(LstFt,NbFt),
        writeln('Nb NbFt :'),
        writeln(NbFt),
        length(Ctr,CtrLeng),
        writeln('Nb Ctr :'),
        writeln(CtrLeng),
           callRec(Att),
          borneRec(LstFt),    
         callRec(Ctr),         
        length(LstFt,SizeMat),
        matrice(M,SizeMat,50),
        limitMatrix(M,LstFt),
  
        pairwiseGenerator(LstFt,M,PWCTRLST,RANKLST),callRec(PWCTRLST),  
       contrainteFDV2(M,LstFt,Ctr,Res),
       writeln(Res),
        callRec(Res),
        alldiffrec(RANKLST),
        flatten(RANKLST,Ilist),  
        my_sort(Ilist,LLL),
        domain(LLL,1,50),
        maximum(K,LLL),
        writeln('Nb Paire :'),
        length(Ilist,Nbpaire),
        writeln(Nbpaire),
        labeling([ff],LLL),
      /*  mytranspose(M,M3),*/
 writeMat('matrix.txt',M),   
       submatrix(M,M2,K),
       mytranspose(M2,M3),
               writeMat('matrix.txt',M3),
        writeln(K).

         
       verify_attributes(Var, Other, Goals).
